### ISSUE TITLE
Migrate CI to a free service

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#1687]
### Description

We may have to migrate off out Buildkite AWS agent scaling account.

Some alternative options:

| Name | Free compute | Notes |
|---|---|---|
| Buildkite | [Unclear](https://buildkite.com/pricing) | Current provider, works great |
| Travis CI | [5 concurrent](https://www.travis-ci.com/plans) | Kinda clunky, IME |
| Circle CI | [1 concurrent](https://circleci.com/pricing/) | No experience |
| GitHub Actions | [20 concurrent](https://help.github.com/en/actions/getting-started-with-github-actions/about-github-actions#usage-limits) | No experience, well integrated into GitHub, Rust (with high CI demand) [switched to it](https://blog.rust-lang.org/inside-rust/2020/04/07/update-on-the-github-actions-evaluation.html) |
| Azure Pipelines | [1 concurrent](https://azure.microsoft.com/en-us/pricing/details/devops/azure-devops-services/) | No experience, Rust previously used it but migrated to Actions |
| Drone CI | [Unclear, maybe 1 concurrent](https://drone.io/enterprise/opensource/#features) | No experience, but heard of it, vaguely |
| AppVeyor | [1 concurrent](https://www.appveyor.com/pricing/) | No experience, but heard of it used for Windows along side Travis (Linux) |

Other lists/comparisons:

- https://github.com/ligurio/awesome-ci

### Checklist for migration

The steps from `.buildkite/pipeline.yml` https://github.com/stellargraph/stellargraph/blob/3867a66b5df85b2b3bb33cd324b95829552008e2/.buildkite/pipeline.yml

- [x] (N/A) :docker::python: build 3.6 runner
- [x] (N/A) :docker::python: build 3.7 runner
- [x] (N/A) :docker::python: build 3.8 runner
- [x] (#1688) :python: 3.6
- [x] (#1688) :python: 3.7
- [x] (#1688) :python: 3.8
- [x] (#1692) :python::book: test notebooks %n
- [x] (#1694) :python::book: test neo4j notebooks against neo4j 4.0
- [x] (#1694) :python::book: test neo4j notebooks against neo4j 3.5
- [x] (#1690) :python-black: format
- [x] (#1697) :python-black::jupyter: check notebook format
- [x] (#1697) :jupyter::book: check notebook text
- [x] (#1717) :book: check demo indexing
- [x] (#1717) :book: check documentation
- [x] (#1715) :shell: format
- [x] (#1690) :shell: shellcheck
- [x] (#1690) :docker: :hadolint: lint Dockerfiles
- [x] (#1715)  :docker: format Dockerfiles
- [x] (#1715)  :prettier::yaml: format YAML
- [x] (#1690) :yaml::lint-roller: lint YAML
- [x] (#1693) :copyright: check copyright headers
- [x] (#1693) :space_invader: check whitespace
- [x] (#1693) :snake: conda build
- [x] (#1707) :memo: annotate with junit

**Comment by timpitman** [comment]
GitHub actions is looking good 👍

**Comment by huonw** [comment]
> Buildkite | Unclear

I emailed Buildkite support, and they said that they don't offer (limited) free agents in any form for the moment, so we'd be able to get the UI and management backend, but we'd have to provide our own agents in some form.
