### ISSUE TITLE
Create stellar-ml library structure, and populate with base classes

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#20]
### Description
- Define the library's structure, base classes, methods, some helper functions, etc.
- Create unit tests for all the library's base classes and helper functions
### User Story
As a: developer of the library
I want: to see a clear structure of base classes to inherit from, their methods, and examples of composing workflows from them.

### Done Checklist (Development)
- [ ] Assumptions of the user story met
- [ ] Produced code for required functionality
- [ ] Branch and Pull Request pass unit tests on CI
- [ ] Peer Code Review Performed
- [ ] Code well commented
- [ ] Documentation in repo
