### ISSUE TITLE
Community Detection

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#239]
### Description  
We need to add community detection functionality to the python library, in some form.  
Possible ways:  
- create a wrapper function for community detection, taking a graph, algorithm name, and parameters as arguments  
- create a demo of embedding-based community detection (representation learning + clustering in the embedding space), and compare its performance with "baseline" community detection algorithms

Some baseline algorithms for community detection:  
- Louvain Community Detection (Python implementation: https://github.com/taynaud/python-louvain)  
- METIS Graph Partitioning (Python wrapper: https://bitbucket.org/kw/metis-python)  
- Algorithms in snap.py: https://snap.stanford.edu/snappy/doc/reference/community.html  
- networkx collection: https://networkx.github.io/documentation/stable/reference/algorithms/community.html

### Done Checklist  
- [x] Epic sub-tasks completed  
- [x] Library includes community detection functionality with:  
  - [x] baseline algorithms (Louvain, METIS, etc.)  
  - [x] representation learning + clustering approach  
- [x] Some sort of community characterisation is implemented  
- [x] Team demo

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

- [ ] Epic sub-tasks completed

- [x] Library includes community detection functionality with:
  - [x] baseline algorithms (Louvain, METIS, etc.)
  - [x] representation learning + clustering approach

- [x] Some sort of community characterisation is implemented

- [x] Team demo
<span data-href="#aha_task_list_end" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://csiro.aha.io/features/SGML-3

**Comment by alezeia** [comment]
test comment for aha
