### ISSUE TITLE
Model Interpretability

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#247]
### Description  
We need to extent the `stellargraph` library to include model interpretability.

### Done Checklist  
- [x] Scope of "model interpretability" is well defined (e.g., interpretation of network embedding via taxonomy induction)  
- [x] Model interpretability functionality is implemented (within the defined scope) and tested  
- [ ] Demos/tutorials showing how to use model interpretability are added to the library  
- [x] Team demos

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://csiro.aha.io/features/SGML-1

**Comment by youph** [comment]
@annitrolla I'll add Huijin to this once he is added to our github

**Comment by timpitman** [comment]
closing the epic - only one task remaining which can go ahead on its own.
