### ISSUE TITLE
New ML Algorithms

### ISSUE THREAD

**Issue by youph** [stellargraph/stellargraph#252]
### Description and Checklist

Graph ML algorithms to add to the Python library:   
- [x] GAT (Graph Attention Network)   
  - [x] implemented  
  - [x] test coverage  
  - [x] demo added  
- [x] Saliency maps, node and link importance
  - [x] implemented  
  - [ ] test coverage  
  - [ ] demo added  
- [x] Simple GCN   
  - [x] implemented  
  - [ ] test coverage  
  - [x] demo added  
- [ ] word2vec   
  - [ ] implemented  
  - [ ] test coverage  
  - [ ] demo added  
- [ ] Scalable GAT (optional, subject to Ke's research outcome)  
  - [ ] implemented  
  - [ ] test coverage  
  - [ ] demo added

<span data-href="#aha_task_list_start" data-version="v2" data-aha="Do not remove this tag. Used for Aha! syncing."/>

Aha! Link: https://csiro.aha.io/features/SGML-34

**Comment by timpitman** [comment]
Closing this long-running epic - work will continue in individual tasks, with new epics created for major pieces of work.
