### ISSUE TITLE
Ransomware detection in a massive blockchain network

### ISSUE THREAD

**Issue by annitrolla** [stellargraph/stellargraph#281]
The project requires collaboration from the platform and ml team along with the domain experts to create a use case of ransomware detection

### Description
This epic covers the following activities:
- [ ] Create a tool for sampling from the network to use in machine learning downstream tasks (platform)
- [ ] Create a machine learning approach to solve the problem (ml-team)
- [ ] Create a pipeline between sampling and modelling in order to modify parameters
- [ ] Build a model using the whole network
  

### Done Checklist
- [ ] All of the above covered
