### ISSUE TITLE
New StellarGraph: convert tests and demos to use pandas not networkx

### ISSUE THREAD

**Issue by huonw** [stellargraph/stellargraph#717]
### Description

In #662 #668, we add a new implementation of the `StellarGraph` class. Only a few tests and demos are converted to use the new functionality, we should convert the rest. NetworkX support (#715) can be tested explicitly, separately.

The new form looks like `StellarGraph(nodes=..., edges=...)`, where the arguments are some sort of dictionary involving pandas dataframes.

Files using the old form (in decreasing order of number of occurrences):

Main library/tests:

- [x] `tests/core/test_graph.py` (19) @huonw #998
- [x] `tests/mapper/test_full_batch_generators.py` (17) @huonw  #1000
- [x] `tests/test_utils/graphs.py` (9) @huonw #999
- [x] `tests/mapper/test_node_mappers.py` (9) @huonw #1005 #1014 
- [x] `tests/layer/test_gcn.py` (7) @huonw #999
- [x] `tests/layer/test_appnp.py` (7)  @huonw #999
- [x] `tests/data/test_biased_random_walker.py` (7) @huonw  #1004
- [x] `stellargraph/core/graph.py` (7) (false positives)
- [x] `tests/mapper/test_link_mappers.py` (4) @huonw #1005
- [x] `tests/utils/test_ensemble.py` (2) @huonw #1014
- [x] `tests/layer/test_ppnp.py` (2) @huonw #999
- [x] `tests/data/test_heterogeneous_breadth_first_walker.py` (2) @huonw #1004
- [x] `tests/mapper/test_directed_node_generator.py` (1) @huonw #1005 #1014
- [x] `tests/mapper/test_cluster_gcn_node_mapper.py` (1) @huonw #1005
- [x] `tests/mapper/test_benchmark_generators.py` (1) @huonw #1005
- [x] `tests/layer/test_cluster_gcn.py` (1) @huonw #999
- [x] `tests/data/test_temporal_random_walker.py` (1) @huonw
- [x] `tests/data/test_node_splitter.py` (1) @huonw #1004
- [x] `tests/data/test_metapath_walker.py` (1) @huonw #1004
- [x] `tests/data/test_directed_breadth_first_sampler.py` (1) @huonw #1004
- [x] `tests/data/test_breadth_first_walker.py` (1) @huonw #1004

Demos (many fixed as part of #812):

- [x] `demos/link-prediction/graphsage/cora-links-example.py` (3)
- [x] `demos/ensembles/ensemble-link-prediction-example.ipynb` (3) #1018
- [ ] `demos/calibration/calibration-pubmed-link-prediction.ipynb` (3) #1026
- [ ] `demos/node-classification/node2vec/stellargraph-node2vec-weighted-random-walks.ipynb` (2) #1018 #1026
- [x] `demos/node-classification/graphsage/graphsage-pubmed-inductive-node-classification-example.ipynb` (2)
- [x] `demos/node-classification/graphsage/graphsage-cora-example.py` (2)
- [x] `demos/link-prediction/random-walks/main.py` (2) #1018
- [x] `demos/link-prediction/graphsage/cora-links-example.ipynb` (2) #1018
- [x] `demos/link-prediction/gcn/cora-gcn-links-example.ipynb` (2) #1018
- [x] `demos/link-prediction/attri2vec/stellargraph-attri2vec-DBLP.ipynb` (2) #1018
- [x] `demos/use-cases/hateful-twitters.ipynb` (1) #1018
- [x] `demos/node-classification/sgc/sgc-node-classification-example.ipynb` (1)
- [x] `demos/node-classification/rgcn/rgcn-aifb-node-classification-example.ipynb` (1)
- [x] `demos/node-classification/node2vec/stellargraph-node2vec-node-classification.ipynb` (1)
- [x] `demos/node-classification/hinsage/yelp-example.py` (1) #1018
- [x] `demos/node-classification/gcn/gcn-cora-example.py` (1)
- [x] `demos/node-classification/gat/gat-cora-example.py` (1)
- [x] `demos/node-classification/cluster-gcn/cluster-gcn-node-classification.ipynb` (1)
- [x] `demos/node-classification/attri2vec/attri2vec-citeseer-node-classification-example.ipynb` (1)
- [x] `demos/link-prediction/hinsage/movielens-recommender.py` (1)
- [x] `demos/link-prediction/hinsage/movielens-recommender.ipynb` (1)
- [x] `demos/interpretability/gcn/node-link-importance-demo-gcn.ipynb` (1) #1017 
- [x] `demos/interpretability/gcn/node-link-importance-demo-gcn-sparse.ipynb` (1) #1017
- [x] `demos/interpretability/gcn/hateful-twitters-interpretability.ipynb` (1) #1018
- [x] `demos/interpretability/gat/node-link-importance-demo-gat.ipynb` (1) #1017
- [x] `demos/ensembles/ensemble-node-classification-example.ipynb` (1) #986
- [x] `demos/embeddings/watch-your-step-cora-demo.ipynb` (1) #1021 
- [x] `demos/embeddings/stellargraph-node2vec.ipynb` (1)
- [x] `demos/embeddings/stellargraph-metapath2vec.ipynb` (1)
- [x] `demos/embeddings/stellargraph-attri2vec-citeseer.ipynb` (1)
- [x] `demos/community_detection/attacks_clustering_analysis.ipynb` (1) #1018
- [x] `demos/calibration/calibration-pubmed-node-classification.ipynb` (1)

Computed using 

```shell
git grep 'Stellar.*Graph(' -- '*.py' '*.ipynb' | grep -v 'nodes=' | cut -f1 -d: | sort | uniq -c | sort -rn | sed 's/ *\([0-9]*\) \(.*\)/- [ ] `\2` (\1)/' 
```

(Plus some manual editing)

**Comment by huonw** [comment]
Some of the notebooks have been converted, and some of the tests, but there's still many calls to `StellarGraph(some_networkx_graph)`. I've updated the PR description with a summary.

**Comment by huonw** [comment]
One route to do this for notebooks would potentially be #812.

**Comment by huonw** [comment]
As noted in https://github.com/stellargraph/stellargraph/pull/891#discussion_r381052282, once we've done this, we can add a deprecation warning for the old `StellarGraph` constructor form, and move the deprecated arguments to `**kwargs` to be less obtrusive.
