### ISSUE TITLE
New StellarGraph class backed by NumPy and Pandas to replace NetworkX

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#752]
### Description

This is an epic to cover the work of our new StellarGraph class backed by NumPy and Pandas instead of NetworkX.

Child issues:

- [x] #174: Make the EdgeSplitter return StellarGraph instead of Networkx graph
- [x] #662: New StellarGraph class backed by Pandas instead of NetworkX
- [x] #715: convert from networkx
- [x] #716: implement unimplemented methods
- [x] #717: convert tests and demos to use pandas not networkx
- [ ] #718: return columnar/numpy-based representations from functions where possible
- [x] #723: streamline and document constructor
- [x] #761: calling `create_graph_schema` with `nodes=...` argument results in an error
- [x] #763: to_adjacency_matrix is not symmetric for undirected graphs
- [x] #766: in_nodes/out_nodes gives only directed edges for undirected graphs
- [x] #768: `_edge_weights` throws NameError
- [x] #770: `neighbors(isolated node)` throws "IndexError: arrays used as indices must be of integer (or boolean) type"
- [ ] #772: coordinating column indexing and selection is difficult
- [x] #774: creating with no nodes or no edges throws "ValueError: No objects to concatenate"
- [x] #775: `.node_type` returns a pandas.Index sequence instead of a single node type 
- [x] #868: `node-link-importance-demo-gat.ipynb` demo fails with `ValueError: 7 is not in list`
- [x] #870: Have an explicit API for working with sequential-integer-labeled nodes, edges and their types
- [x] #894: Error handling could be improved when node IDs appear in edges but not in nodes
- [x] #1030: add deprecation warning for legacy constructor
- [x] #1039: remove use of networkx from Cora link prediction examples
- [x] #1040: remove use of NetworkX from weighted Node2vec notebook

### User Story

**As a data scientist, I want a more memory efficient and performant graph storage in StellarGraph, so that I can work with larger graphs**

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo
