### ISSUE TITLE
Make the CI pipeline in Buildkite more robust

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#753]
### Description

While our CI pipeline in Buildkite does run tests and check formatting, there are some notable omissions:
* demo notebooks and scripts are not tested
* notebook formatting is not verified
* code coverage results are hidden and not updating coveralls

There are also some potential extensions:
* type checking (via mypy)

Child issues:

- [x] #575 Check demo scripts and notebooks on CI
- [ ] #686 Consider using static type annotations
- [x] #748 Migrate code coverage from coveralls to codecov
- [ ] #749 Test all algorithms with randomness for reproducibility
- [ ] #758 Update link prediction demo script to use new datasets module to access Cora and BlogCatalog3
- [ ] #811 Bring unsupported datasets into the datasets module
- [ ] #818 Some demo notebooks can't be tested on CI due to using datasets that have licensing restrictions preventing automatic download
- [ ] #819 Some notebooks out-of-memory when running on CI
- [x] #820 Some notebooks take a long time to run on CI and therefore aren't tested
- [x] #833 metapath2vec demo notebook too slow to run on CI
- [x] #917 Notebooks are sometimes tested twice (or none-ce) on CI

### User Story

**As a StellarGraph developer, I want a CI pipeline that checks as much of my code as possible, so that once passed CI, I know it's functioning correctly.**

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo
