### ISSUE TITLE
GraphWave structural embeddings algorithm

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#822]
### Description

This is an epic to cover development of the GraphWave structural embeddings algorithm. The GraphWave paper (https://arxiv.org/pdf/1710.10321.pdf) proposes a method of calculating structural embeddings using graph spectral methods. These structural embeddings could be useful for node classification tasks where the node classes of interest do not form a community but have a distinct structural role in graph.

Child issues:

- [x] https://github.com/stellargraph/stellargraph/pull/814
- [ ] #853: chebyshev polynomials
- [ ] #815: unit tests
- [ ] #830: more inductive and scaleable
- [ ] #903: blog post

### User Story

As a: data scientist
I want: a method of obtaining structural embeddings
so that: I can perform node classification on data sets without communities

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo
