### ISSUE TITLE
Knowledge Graph support

### ISSUE THREAD

**Issue by timpitman** [stellargraph/stellargraph#824]
### Description

Support at least one "knowledge graph" algorithm, expanding the applications of StellarGraph.

See Accenture's AmpliGraph for some potential algorithms and datasets: https://github.com/Accenture/AmpliGraph

Subissues:

- [ ] #755: DistMult
- [ ] #756: ComplEx
- [ ] #862: ComplEx: reproduce the paper results

### User Story

**As a data scientist working with StellarGraph, I want access to knowledge graph algorithms **

### Done Checklist

- [ ] Produced code for required functionality
- [ ] Tests written and coverage checked
- [ ] Code review performed
- [ ] Documentation on Google Docs  (if applicable)
- [ ] Documentation in repo
- [ ] Version number reflects new status
- [ ] CHANGELOG.md updated
- [ ] Team demo
